#theme: jekyll-theme-cayman
# Setup
title:       "Inducing Hierarchical Compositional Model by Sparsifying Generator Network"
baseurl:      "/Deep-Sparse-Generator"

# About/contact
author:
  name:       Andy Xing
  url:        https://github.com/andyxingxl

#Others
markdown: kramdown
